USE_GPU = False
USE_CROP = False
CROP_SIZE = [32, 32]
IMAGE_SIZE = [320, 480]
EPOCHS = 3
BatchSize = 40
learning_rate = 0.01
input_channels = 1
output_channels = 1
highest_level_features = 1
depth = 1
rank = 1
MODEL_TO_EVALUATE = 'models/UNet_model.pt'